apiVersion: v1
kind: PersistentVolume
metadata:
  name: resumeai-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  gcePersistentDisk:
    pdName: resumeai-disk
    fsType: ext4
